// Conteúdo de exemplo: matérias da Edição nº 01 (10/09/2026) do Jornal Cidades do Vale.
// Parágrafos iniciados com "## " viram intertítulos; com "> " viram citação.

export const posts = [
  {
    title: "Paulinho do Esporte amplia investimentos na infraestrutura da cidade",
    subtitle: "Entre as ações está a recuperação da infraestrutura urbana e atenção à zeladoria",
    city: "pedro-de-toledo",
    category: "cidades",
    highlight: "manchete",
    cover: "p1_5_332x440.jpg",
    caption: "Prefeito Paulinho do Esporte está dinamizando a gestão pública de Pedro de Toledo",
    date: "2026-09-10T08:00:00-03:00",
    body: [
      "O prefeito de Pedro de Toledo, Paulo Eduardo Alves (Paulinho do Esporte), está avançando com as metas prioritárias de seu governo, sobretudo na área de infraestrutura. A cidade vem recebendo obras em diversos bairros, seguindo à risca o cronograma elaborado no início da gestão, com foco na recuperação da malha viária urbana e rural.",
      "## A lista é grande",
      "As principais intervenções são de recapeamento das vias urbanas, manutenção das estradas rurais e ações diversificadas de zeladoria. “Queremos chegar ao nosso terceiro ano de governo com uma cidade mais estruturada, para então iniciarmos a fase seguinte da gestão, onde pretendemos priorizar o desenvolvimento econômico, com medidas que favoreçam a geração de emprego e oportunidades”.",
      "## Investimentos",
      "Desde janeiro de 2025, a cidade recebe um volume considerável de obras. Dados do departamento responsável pelo setor registram um grande número de vias beneficiadas com serviços de pavimentação ou repavimentação. Paulinho afirma que as melhorias estruturais estão sendo possíveis graças ao plano de contenção e otimização de despesas que implantou logo após a posse, em janeiro do ano passado, e que apresentaram bons resultados. “Conseguimos organizar as contas e por isso temos agora mais fôlego para investir em obras”.",
      "[img:p3_5_340x289.jpg]",
      "## Lazer nos bairros",
      "Os investimentos em infraestrutura se estendem também ao lazer. Está em fase de projeto a revitalização e melhorias no lazer do bairro Nóbrega, que contará com equipamentos para exercícios ao ar livre e atividades coletivas (academia da saúde), playground completo com a devida atenção à acessibilidade, já que as calçadas serão adaptadas e haverá piso intertravado para facilitar a circulação dos frequentadores do novo espaço.",
      "> “Pedro de Toledo vive um momento inédito em se tratando de gestão pública. Nosso objetivo é encerrar o ano com o maior volume de investimentos da história da cidade. Vamos transformar as possibilidades em realidade”, finalizou o prefeito.",
    ],
  },
  {
    title: "Pariquera sedia a 4ª Expoplantas Rodeo Festival unindo agricultura e turismo",
    kicker: "Atrações",
    subtitle: "Capital das Plantas Ornamentais promove nova edição da sua grande festa nativa",
    city: "pariquera-acu",
    category: "turismo",
    highlight: "destaque",
    cover: "p1_6_502x250.jpg",
    caption: "A cantora Mariana Fagundes é a atração do dia 12 de setembro",
    date: "2026-09-10T09:00:00-03:00",
    body: [
      "De 10 a 13 de setembro, Pariquera-Açu realiza a 4ª Expoplantas Rodeo Festival, reunindo agronegócio, paisagismo, tecnologia, capacitação, turismo e entretenimento. Promovido pela Prefeitura Municipal, o evento reforça a identidade de Pariquera-Açu como Capital das Plantas Ornamentais do Estado de São Paulo, título concedido oficialmente em 2023.",
      "As atrações artísticas serão a dupla Luiz Miguel & Daniel, Patrick & Pagiel e a cantora Mariana Fagundes, que farão parte da segunda metade do evento, no período noturno, com montarias e shows.",
      "A realização da Expo integra uma estratégia de valorização da produção rural que tem no prefeito Wagner Costa um dos principais incentivadores. Foi a partir de sua iniciativa que o projeto “Pariquera-Açu – Capital das Plantas Ornamentais” avançou na Assembleia Legislativa paulista.",
      "A vocação do município para o setor tem raízes históricas. As pesquisas com plantas ornamentais começaram ainda na década de 1960 e, atualmente, Pariquera-Açu responde por cerca de 67% da produção regional voltada à jardinagem, reunindo aproximadamente trezentos produtores.",
      "[img:p7_2_332x405.jpg]",
      "## Negócios, tecnologia e conhecimento",
      "Para o secretário municipal de Agricultura, Bruno Rangel Arcari, a Expo representa uma oportunidade para aproximar produtores de novas tecnologias, fornecedores, instituições financeiras e potenciais compradores. Nesta edição, serão cerca de quarenta estandes, com viveiros, empresas de jardinagem e decoração, fornecedores de vasos, estufas, substratos e adubos, além de máquinas, equipamentos e serviços ligados ao agronegócio.",
      "## Agricultura e turismo",
      "Uma das novidades desta edição será o circuito de visitas às propriedades produtoras de plantas ornamentais. A Secretaria de Turismo também trabalha na elaboração do Mapa Turístico, na sinalização turística e na estruturação de uma rota rural que conectará produtores, propriedades, gastronomia e experiências locais.",
      "**Local:** Centro de Exposições dos Imigrantes, Avenida Olímpica, s/n, entrada principal da cidade de Pariquera-Açu. Mais informações no Instagram @expoplantaspariquera.",
    ],
  },
  {
    title: "Paraná Pesquisas: Tarcísio lidera disputa pelo governo de SP",
    kicker: "Eleições 2026",
    subtitle: "Levantamento foi realizado entre 16 e 18 de agosto; período marca os primeiros dias da campanha eleitoral",
    category: "eleicoes-2026",
    highlight: "destaque",
    cover: "p1_11_329x385.jpg",
    caption: "Governo de São Paulo, primeiro turno. Fonte: Paraná Pesquisas",
    date: "2026-09-10T10:00:00-03:00",
    body: [
      "O governador de São Paulo, Tarcísio de Freitas (Republicanos), aparece com 50% das intenções de voto na disputa pelo governo do estado, segundo pesquisa do Instituto Paraná Pesquisas. O ex-ministro da Fazenda Fernando Haddad (PT) tem 33,8%.",
      "A diferença entre os dois é de 16,2 pontos percentuais. Na pesquisa anterior do instituto, realizada em julho, Tarcísio tinha 48,5% e Haddad, 35,1%. Com isso, a vantagem do governador passou de 13,4 para 16,2 pontos percentuais.",
      "Na sequência aparecem Vera Lúcia (PSTU), com 1,5%; Carlos Machado (PCB) e Vivian Mendes (UP), ambos com 0,8%; Izadora Dias (PCO) e Policial Edjane (Agir), com 0,4% cada. Outros 7,5% dos entrevistados afirmaram que não votariam em nenhum dos candidatos, em branco ou nulo, e 4,8% não souberam ou não quiseram responder.",
      "## Segundo turno",
      "Em um cenário de segundo turno apenas entre Tarcísio e Haddad, o candidato à reeleição também aparece à frente, com 53%, contra 36,9% do petista. Em julho, os dois tinham 51,8% e 38,3%, respectivamente.",
      "A pesquisa ouviu 1.680 eleitores em 80 municípios paulistas entre os dias 16 e 18 de agosto. A margem de erro é de 2,4 pontos percentuais, com nível de confiança de 95%. O levantamento está registrado no Tribunal Superior Eleitoral (TSE) sob o número SP-08913/2026.",
    ],
  },
  {
    title: "Wagner Costa leva demandas do Vale do Ribeira a Tarcísio",
    kicker: "Plano de governo",
    subtitle: "As propostas tratam de saúde, infraestrutura, agricultura e turismo e já foram incorporadas ao documento oficial da campanha do governador",
    city: "pariquera-acu",
    category: "politica",
    highlight: "destaque",
    cover: "p3_3_329x184.jpg",
    caption: "Wagner Costa liderou o levantamento de demandas do Vale do Ribeira",
    date: "2026-09-10T11:00:00-03:00",
    body: [
      "O prefeito de Pariquera-Açu e presidente do Consórcio de Desenvolvimento Intermunicipal do Vale do Ribeira (CODIVAR), Wagner Costa, apresentou importantes sugestões ao plano de governo do governador e candidato à reeleição, Tarcísio de Freitas.",
      "Levantadas e catalogadas através de diálogo com as prefeituras da região, e ainda em reuniões e consultas às associações representativas, lideranças sociais e à sociedade civil, as propostas abordam investimentos importantes e vitais para o futuro da região, nas áreas de saúde, infraestrutura e turismo, entre outros segmentos.",
      "Wagner Costa acredita que a região enfrenta desafios históricos que limitam seu pleno potencial, notadamente em infraestrutura logística e turística, acesso qualificado à saúde, modernização da educação e dinamismo econômico.",
      "## Infraestrutura e logística",
      "O conjunto de propostas apresenta a necessidade de um Plano Regional de Infraestrutura e Logística, a fim de contornar os graves problemas de escoamento da produção, acesso turístico e mobilidade urbana entre as cidades do Vale, e medidas para sanar o que os prefeitos consideram uma subutilização do potencial turístico e cultural da região.",
      "Na agricultura, o documento elaborado pelo Codivar aponta como principal entrave o baixo valor agregado na produção agrícola e as dificuldades de acesso a mercados competitivos pelas cadeias produtivas locais.",
    ],
  },
  {
    title: "Pedro de Toledo alcança marca histórica no IDEB",
    kicker: "Educação municipal",
    subtitle: "Resultado de 2025 supera a expectativa da Secretaria de Educação",
    city: "pedro-de-toledo",
    category: "educacao",
    highlight: "secundaria",
    cover: "p3_4_337x241.jpg",
    date: "2026-09-11T08:30:00-03:00",
    body: [
      "Pedro de Toledo registrou avanço histórico no Índice de Desenvolvimento da Educação Básica (IDEB) 2025 e alcançou 6,6 nos anos iniciais do Ensino Fundamental da rede municipal. O resultado representa crescimento em relação aos 6,1 registrados em 2023 e supera a expectativa interna do Departamento Municipal de Educação, que trabalhava com a meta de chegar a 6,2.",
      "O índice de 6,6 é o melhor resultado registrado pelo município na série histórica apresentada pelo Inep. Em 2021 e 2023, Pedro de Toledo havia alcançado 6,1. Antes disso, o município registrou 5,8 em 2017 e 6,1 em 2015 e 2019.",
      "> “Subir para 6,6 foi uma alegria gigantesca para toda a administração e equipe do Departamento de Educação”, disse o prefeito Paulinho do Esporte.",
      "Segundo a administração, as iniciativas têm como objetivo criar condições para garantir a frequência e a permanência dos alunos na escola e, no longo prazo, contribuir para resultados ainda melhores na aprendizagem.",
    ],
  },
  {
    title: "Educação de Itariri obtém resultado histórico no IDEB",
    kicker: "Melhor índice",
    subtitle: "Rede municipal conquista nota 7,0 no IDEB 2025 e alcança o melhor índice entre os municípios com mais de 15 mil habitantes da Baixada Santista e do Vale do Ribeira",
    city: "itariri",
    category: "educacao",
    highlight: "secundaria",
    cover: "p4_1_332x290.jpg",
    caption: "Prefeito Carlos Rocha",
    date: "2026-09-11T10:00:00-03:00",
    body: [
      "A educação municipal de Itariri alcançou um resultado histórico. No IDEB 2025, a rede municipal de ensino conquistou nota 7,0, o maior resultado já registrado pelo município no Índice de Desenvolvimento da Educação Básica.",
      "O resultado coloca Itariri em posição de destaque regional. Considerando os municípios com mais de 15 mil habitantes, Itariri apresentou o melhor índice entre as cidades da Baixada Santista e do Vale do Ribeira. A nota também supera as médias estadual e nacional, que ficaram em 6,6 e 6,3, respectivamente.",
      "## Um resultado construído dentro das escolas",
      "Mais do que um número, o resultado representa o trabalho realizado diariamente por professores, equipes gestoras, profissionais da educação, estudantes e famílias.",
      "## Educação que olha para o futuro",
      "O IDEB 2025 estabelece um novo marco para a educação de Itariri. Alcançar 7,0 é motivo de orgulho, mas também representa um novo desafio: continuar avançando, aprimorando o ensino e garantindo cada vez mais oportunidades para os alunos da rede municipal.",
    ],
  },
  {
    title: "ANTT confirma EPR como vencedora para assumir controle da Régis Bittencourt",
    subtitle: "Agência encerra fase de recursos e encaminha resultado à diretoria antes da mudança de gestão",
    category: "estradas",
    highlight: "secundaria",
    cover: "p4_3_331x332.jpg",
    date: "2026-09-12T09:00:00-03:00",
    body: [
      "A Agência Nacional de Transportes Terrestres (ANTT) publicou em 20 de agosto de 2026 o Comunicado Relevante nº 9, que confirmou o resultado definitivo do Processo Competitivo nº 1/2026 para a alienação de 100% das ações da Autopista Régis Bittencourt S.A., concessionária da BR-116/SP/PR.",
      "Segundo o comunicado, a EPR Participações S.A. foi confirmada como vencedora, com proposta correspondente a desconto de 22,53% sobre a Tarifa Básica de Pedágio. O prazo recursal previsto no edital transcorreu sem recursos das proponentes.",
      "## Novo ciclo de investimentos",
      "A principal mudança para quem utiliza a rodovia está relacionada ao novo ciclo de investimentos previsto para a concessão. O contrato estima cerca de R$ 7,2 bilhões em investimentos, destinados à ampliação da capacidade, recuperação da infraestrutura, manutenção e melhorias na operação da BR-116/SP/PR. Entre as intervenções previstas estão aproximadamente 69 quilômetros de faixas adicionais e 33 quilômetros de vias marginais.",
      "## Uma estrada importante para São Paulo e Paraná",
      "O trecho concedido da BR-116 tem cerca de 383 quilômetros e conecta São Paulo a Curitiba. A rodovia também integra rotas de ligação com o Porto de Paranaguá, no Paraná, e é estratégica para o deslocamento de mercadorias entre os dois estados.",
    ],
  },
  {
    title: "CBH-RB completa 30 anos com novas metas para fortalecer a gestão das águas",
    kicker: "Gestão das águas",
    subtitle: "Comitê define prioridades para 2026-2029 e aprova investimentos de mais de R$ 6 milhões em projetos para a região",
    city: "vale-do-ribeira",
    category: "meio-ambiente",
    highlight: "secundaria",
    cover: "p5_2_329x230.jpg",
    caption: "Divulgação CBH-RB",
    date: "2026-09-12T11:00:00-03:00",
    body: [
      "O Comitê da Bacia Hidrográfica do Ribeira de Iguape e Litoral Sul (CBH-RB) completa 30 anos de atuação em 2026. Criado em 1996, o órgão reúne representantes dos municípios, do Estado e da sociedade civil para discutir prioridades e definir ações para os recursos hídricos do Vale do Ribeira e Litoral Sul.",
      "Para o presidente da entidade, Ricardo Cordeiro de Paula, as três décadas de atuação consolidaram uma gestão mais democrática e participativa das águas. A nova etapa tem como desafio preparar a região para eventos climáticos extremos.",
      "## Segurança hídrica e prevenção",
      "Um dos principais desafios é a convivência com as cheias. O Rio Ribeira responde rapidamente às chuvas fortes em suas cabeceiras, exigindo sistemas de alerta, prevenção e capacidade de resposta dos municípios.",
      "## Investimentos e participação",
      "Na 116ª Assembleia do CBH-RB, realizada em 31 de agosto em Registro, representantes do Estado, municípios e sociedade civil aprovaram o financiamento de 14 empreendimentos que, somados às contrapartidas, ultrapassam R$ 6 milhões, contemplando drenagem, planejamento, coleta seletiva e educação ambiental.",
    ],
  },
  {
    title: "Pedro de Toledo leva atendimento odontológico aos bairros rurais",
    subtitle: "Projeto inédito começou no bairro Morro Branco, com a meta de ampliar o acesso à saúde bucal nas comunidades distantes",
    city: "pedro-de-toledo",
    category: "cidades",
    cover: "p5_3_329x292.jpg",
    caption: "A Unidade Odontológica Móvel é um projeto inédito em Pedro de Toledo",
    date: "2026-09-13T09:00:00-03:00",
    body: [
      "A prefeitura de Pedro de Toledo iniciou o projeto Saúde Bucal nos Bairros, que está levando atendimento odontológico às comunidades rurais por meio da Unidade Odontológica Móvel, a Odontomóvel. A iniciativa é do Departamento Municipal de Saúde.",
      "A conquista da Odontomóvel foi articulada pelo prefeito Paulinho do Esporte, por meio do Novo PAC, do Governo Federal. Pedro de Toledo está entre os treze municípios do Estado de São Paulo contemplados com a unidade.",
      "São oferecidos procedimentos de atenção básica, como restaurações, limpeza e outros atendimentos compatíveis com a unidade móvel. O agendamento é feito pelos Agentes Comunitários de Saúde.",
    ],
  },
  {
    title: "APM e Codivar assinam acordo de cooperação",
    kicker: "Ações municipalistas",
    subtitle: "A aliança tem como objetivo aproximar as prefeituras do Vale do Ribeira da principal entidade municipalista do país",
    city: "vale-do-ribeira",
    category: "politica",
    cover: "p6_2_331x133.jpg",
    date: "2026-09-14T09:00:00-03:00",
    body: [
      "O Consórcio de Desenvolvimento Intermunicipal do Vale do Ribeira e Litoral Sul (CODIVAR) e a Associação Paulista de Municípios (APM) assinaram um acordo de cooperação técnica. A parceria inaugura uma nova etapa de integração entre as instituições, com foco no compartilhamento de conhecimento, na inovação da gestão pública e no fortalecimento do municipalismo paulista.",
      "O documento foi assinado pelo presidente da APM, Fred Guidoni, e pelo prefeito de Pariquera-Açu e presidente do Codivar, Wagner Costa, durante a assembleia de prefeitos do Vale do Ribeira, em Cajati.",
    ],
  },
  {
    title: "Cidades do Litoral Sul e Vale do Ribeira se destacam no Prêmio Top Destinos Turísticos",
    kicker: "6ª edição",
    subtitle: "Premiação reúne votação popular e avaliação técnica para reconhecer municípios que trabalham o turismo",
    city: "ilha-comprida",
    category: "turismo",
    cover: "p6_6_502x283.jpg",
    date: "2026-09-15T09:00:00-03:00",
    body: [
      "Itanhaém e Peruíbe foram os destaques do Litoral Sul na sexta edição do Prêmio Top Destinos Turísticos, referente a 2025. Itanhaém conquistou o título de Top Campeã na categoria Turismo Cultural, enquanto Peruíbe venceu em Turismo de Pesca.",
      "Criado em 2019, o prêmio reconhece municípios paulistas que trabalham o turismo e estimula as cidades a identificar e desenvolver suas principais vocações, com categorias como Ecoturismo, Turismo Rural, Turismo de Sol e Praia e Turismo Gastronômico.",
      "> “A população faz parte do produto turístico”, afirma Aristides de La Plata Cury, idealizador do Top Destinos Turísticos.",
    ],
  },
  {
    title: "Consaúde fortalece parceria com o Governo de SP",
    subtitle: "Dirigentes do consórcio apresentaram as demandas da região na Secretaria Estadual de Saúde",
    city: "pariquera-acu",
    category: "cidades",
    cover: "p6_5_328x152.jpg",
    date: "2026-09-16T09:00:00-03:00",
    body: [
      "Em reunião na capital, dirigentes do Consórcio Intermunicipal de Saúde do Vale do Ribeira (CONSAÚDE) apresentaram as demandas da região e discutiram propostas para fortalecer a parceria com o Governo do Estado, com a presença do secretário estadual Eleuses Paiva.",
      "Em junho, o Governo do Estado inaugurou o novo prédio do Hospital Regional Dr. Leopoldo Bevilacqua, em Pariquera-Açu, unidade administrada pelo consórcio. A nova estrutura recebeu investimento de R$ 17 milhões e abriga os serviços de Oncologia, Obstetrícia e Neonatologia.",
    ],
  },
  {
    title: "Sebrae-SP e Prefeitura de Registro realizam Feira Encantos do Ribeira",
    kicker: "Sebrae no Vale do Ribeira",
    subtitle: "Considerada a maior vitrine do Vale do Ribeira, a quarta edição da feira valorizou todo o potencial da região",
    city: "registro",
    category: "economia",
    cover: "p7_5_445x376.jpg",
    date: "2026-09-17T09:00:00-03:00",
    body: [
      "A quarta edição da Feira Encantos do Ribeira foi realizada pelo Sebrae-SP em parceria com a Prefeitura de Registro, na Associação Cultural Esportiva de Registro (ACER). Durante todo o fim de semana, a população pôde apreciar uma amostra da gastronomia, da cultura e das tradições regionais, inspirada no projeto ‘Dá Gosto Ser do Ribeira’.",
      "Foram quase 100 expositores, transformando o espaço da ACER numa grande vitrine regional.",
      "## Brasil Honey Show",
      "Apicultores do Vale do Ribeira terão a oportunidade de participar gratuitamente da Brasil Honey Show, considerada a maior feira de apicultura do País, em Botucatu. A participação é viabilizada por uma missão técnica do Sebrae-SP em parceria com a Apivale e a Prefeitura de Barra do Turvo.",
    ],
  },
  {
    title: "Vinícius Leão defende soluções sustentáveis para o Vale",
    kicker: "Futuro do Vale",
    subtitle: "Os principais debates dos candidatos do PSDB nestas eleições estarão na bioeconomia regional, inovação e desenvolvimento sustentável",
    category: "eleicoes-2026",
    cover: "p3_2_322x189.jpg",
    caption: "Vinícius Leão em recente entrevista na Rádio Santa Cecília de Santos",
    date: "2026-09-18T09:00:00-03:00",
    body: [
      "O coordenador regional do PSDB no Vale do Ribeira e Baixada Santista, Vinícius Leão, deu a largada na campanha eleitoral articulando as candidaturas tucanas nas 25 cidades que formam as duas regiões.",
      "> “Acredito que o progresso e a sustentabilidade podem caminhar lado a lado aqui no nosso Vale do Ribeira”, afirmou.",
      "Vinícius ressaltou que as iniciativas relacionadas às cadeias produtivas do turismo, logística e produção rural merecem toda a atenção e o apoio dos candidatos, sobretudo os projetos que já estão em desenvolvimento.",
    ],
  },
  {
    title: "Pedro de Toledo, a cidade verde do Vale",
    kicker: "Curta o Vale!",
    subtitle: "Rica em tradições e roteiros ecológicos, a cidade está ampliando sua infraestrutura para receber ainda mais visitantes nos fins de semana",
    city: "pedro-de-toledo",
    category: "turismo",
    cover: "p8_2_287x356.jpg",
    date: "2026-09-19T09:00:00-03:00",
    body: [
      "Pedro de Toledo é conhecida como uma cidade ecológica por ter cerca de 75% de seu território composto por áreas de preservação ambiental e 100% coberto pelo bioma da Mata Atlântica.",
      "A cidade recebeu seu primeiro impulso em 1912 com a chegada da Estrada de Ferro Sorocabana. Com a emancipação, em 9 de abril de 1949, passou a chamar-se Pedro de Toledo, em homenagem ao estadista e ex-governador paulista.",
      "## Destaques ecológicos e turísticos",
      "A Prefeitura promove atrativos como passeios de bicicleta, cachoeiras e trilhas, como a do Morro Boa Vista. Parte da região integra o entorno do Parque Estadual da Serra do Mar, valorizando o ecoturismo e a proteção de nascentes.",
    ],
  },
  {
    title: "COMTUR de Ilha Comprida reforça planejamento e sustentabilidade",
    kicker: "Desenvolvimento turístico",
    subtitle: "Reuniões discutiram qualificação do setor, infraestrutura, preservação ambiental e ações para fortalecer o turismo durante todo o ano",
    city: "ilha-comprida",
    category: "turismo",
    cover: "p8_6_331x232.jpg",
    date: "2026-09-20T09:00:00-03:00",
    body: [
      "O Conselho Municipal de Turismo (COMTUR) de Ilha Comprida realizou reuniões ordinárias no Espaço Cultural Plínio Marcos, reunindo representantes do poder público, iniciativa privada e sociedade civil.",
      "De acordo com o presidente do COMTUR, Aurélio Pedro da Silva, as discussões reforçaram a necessidade de tratar o turismo como uma política permanente de desenvolvimento, e não apenas como uma atividade concentrada na temporada de verão.",
    ],
  },
  // Opinião
  {
    title: "Tarcísio, o desenvolvimentista",
    type: "editorial",
    category: "opiniao",
    date: "2026-09-10T07:00:00-03:00",
    body: [
      "Se a ordem é o desenvolvimento de São Paulo a todo custo, o governador da locomotiva do Brasil não poderia ser outro: Tarcísio de Freitas, que está prestes a completar quatro anos de um governo dinâmico, pródigo em inovações e fértil em medidas de aceleração e retomada econômica.",
      "Há quem diga que Tarcísio é um político tímido. Também diziam que Mário Covas era um político tímido. Ledo engano. A se considerar estes primeiros quatro anos à frente do Palácio dos Bandeirantes, é possível imaginar que a aura desenvolvimentista de Mário Covas ainda ronda o palácio.",
      "Em linhas gerais, as medidas principais deste governo foram pautadas pelo crescimento econômico, progresso e infraestrutura, com duas dúzias de concessões e PPPs no âmbito do Programa de Parcerias de Investimentos.",
    ],
  },
  {
    title: "O Vale do Ribeira, Vale das Oportunidades",
    type: "artigo",
    category: "opiniao",
    author: "Wilber Rossini",
    authorRole: "Advogado",
    cover: "p2_5_329x200.jpg",
    date: "2026-09-10T07:30:00-03:00",
    body: [
      "Quando pensamos em oportunidades, normalmente associamos o conceito à possibilidade de criar negócios, gerar renda, conquistar novos mercados e ampliar as oportunidades de trabalho. Nesse contexto, o Vale do Ribeira ainda é, para muitas pessoas, um território pouco conhecido e, consequentemente, pouco explorado sob a perspectiva dos negócios e do desenvolvimento turístico.",
      "Essa realidade, entretanto, representa justamente uma de suas maiores potencialidades. Conhecer a região, identificar suas vocações e transformar recursos e atrativos ainda pouco explorados em produtos e experiências turísticas representa uma grande oportunidade para empreendedores.",
      "Entre as principais oportunidades de negócios estão as agências de receptivo turístico, que podem inovar por meio da criação de roteiros integrados, oferecendo ao visitante uma experiência completa e segura.",
      "Outro segmento com grande potencial é o de meios de hospedagem. Empreendimentos que incorporem elementos da cultura, da história e das características naturais do Vale do Ribeira podem oferecer uma experiência diferenciada e conectada ao território. É essa conexão que transforma uma viagem em experiência.",
      "*Wilber Rossini é advogado e consultor de políticas públicas. Já exerceu o cargo de superintendente do Codivar e Consaúde.*",
    ],
  },
  // O Vale em Foco (notas)
  {
    title: "Coordenador regional",
    type: "nota",
    category: "politica",
    subtitle: "Wagner Costa, prefeito de Pariquera-Açu, foi confirmado como coordenador político da campanha à reeleição de Tarcísio de Freitas no Vale do Ribeira.",
    date: "2026-09-10T06:00:00-03:00",
    body: [
      "Wagner Costa, prefeito de Pariquera-Açu em segundo mandato, foi confirmado como coordenador político da campanha à reeleição de Tarcísio de Freitas ao governo paulista na região administrativa do Vale do Ribeira. “Recebi este convite com bastante satisfação. Me sinto honrado e super motivado para estar cuidando da campanha aqui no Vale”, afirmou.",
    ],
  },
  {
    title: "Adote uma Praça",
    type: "nota",
    city: "cananeia",
    category: "cidades",
    subtitle: "Cananéia abriu chamamento público para que moradores, empresas e parceiros colaborem com a revitalização de espaços públicos.",
    date: "2026-09-10T06:05:00-03:00",
    body: [
      "Está em curso em Cananéia o chamamento público denominado Adote uma Praça, criado pela prefeitura para permitir que pessoas físicas, empresas, comerciantes, artistas, moradores e parceiros possam colaborar com a revitalização e o embelezamento de espaços públicos. As doações serão destinadas especialmente às ações na Praça da Tiduca e na Rua do Artesão.",
    ],
  },
  {
    title: "Produtores rurais",
    type: "nota",
    category: "economia",
    subtitle: "O Vale avança na implantação do Serviço de Inspeção Municipal Consorciado, liderado pelo Sebrae-SP.",
    date: "2026-09-10T06:10:00-03:00",
    body: [
      "O Vale do Ribeira está avançando na implantação do Serviço de Inspeção Municipal Consorciado, iniciativa que busca fortalecer a produção e a comercialização de produtos de origem animal na região. A iniciativa é liderada pelo Sebrae-SP.",
    ],
  },
  {
    title: "Representatividade",
    type: "nota",
    category: "politica",
    subtitle: "Deputado Paulo Corrêa Jr. relacionou mais de R$ 41 milhões em investimentos destinados a 18 municípios da região.",
    date: "2026-09-10T06:15:00-03:00",
    body: [
      "Em balanço de ações de mandato, o deputado estadual Paulo Corrêa Jr. (Republicanos) relacionou mais de R$ 41 milhões em investimentos destinados a 18 municípios da região do Vale do Ribeira, nas áreas de saúde, educação, turismo e infraestrutura.",
    ],
  },
  {
    title: "Foco no turismo",
    type: "nota",
    city: "pariquera-acu",
    category: "turismo",
    subtitle: "Depois da Feibanana e da Festa das Nações, Pariquera-Açu se firma como o maior palco de eventos da região.",
    date: "2026-09-10T06:20:00-03:00",
    body: [
      "Pariquera-Açu está se tornando o maior palco de eventos turísticos e de lazer da região. Depois do sucesso da Feibanana e da Festa das Nações, a cidade prepara mais uma atividade de grande porte: a 4ª Expoplantas, valorizando o fato de ser a capital das plantas ornamentais de São Paulo.",
    ],
  },
  {
    title: "Aconteceu no Vale: APRECESP se reuniu em Cananéia",
    type: "nota",
    city: "cananeia",
    category: "turismo",
    subtitle: "Encontro reuniu 25 municípios e marcou os 40 anos de atuação da associação no turismo paulista.",
    date: "2026-09-10T06:25:00-03:00",
    body: [
      "A APRECESP (Associação das Prefeituras das Cidades Estância do Estado de São Paulo) realizou em 15 de agosto a 4ª Reunião de Prefeituras de 2026, no Centro Comunitário do Rocio, em Cananéia. O encontro reuniu 25 municípios e integra a agenda da associação, que marca seus 40 anos de atuação no turismo paulista.",
    ],
  },
];

export const ads = [
  { title: "GRAACC 35 anos: Cheio de Vida", advertiser: "GRAACC", image: "p1_2_1024x217.jpg", link: "https://graacc.org.br", position: "meio" },
  { title: "Pró-Sangue: a vida de alguém depende de você", advertiser: "Pró-Sangue", image: "p3_1_1024x198.jpg", link: "https://www.prosangue.sp.gov.br", position: "materia" },
  { title: "Anuncie no JCV", advertiser: "Jornal Cidades do Vale", image: "anuncie-lateral.png", link: "https://wa.me/5513991177371", position: "lateral" },
];
